# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "08747e1aee44008f3206d0e0d4c1b130"
name = "PredictaCore-App"
application_url = "https://predictaseo-core-production.up.railway.app"
embedded = true
handle = "predictacore-app"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = ["shop/update"]
  uri = "/webhooks/shop/update"

  [[webhooks.subscriptions]]
  topics = ["app_subscriptions/update"]
  uri = "/webhooks/app/subscriptions_update"

  [[webhooks.subscriptions]]
  topics = ["products/delete"]
  uri = "/webhooks/products/delete"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "/webhooks/compliance"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_content,write_content,read_locales,write_translations,read_markets,read_themes,write_themes,read_locations,read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects,read_reports"

[app_proxy]
url = "https://predictaseo-core-production.up.railway.app/proxy"
subpath = "predictacore"
prefix = "apps"

[auth]
redirect_urls = [
  "https://predictaseo-core-production.up.railway.app/auth/callback",
  "https://predictaseo-core-production.up.railway.app/auth/shopify/callback",
  "https://predictaseo-core-production.up.railway.app/api/auth/callback"
]
