# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "08747e1aee44008f3206d0e0d4c1b130"
name = "PredictaCore-App"
application_url = "https://predictaseo-core-production.up.railway.app"
embedded = true
handle = "predictacore-app"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_content,write_content,read_locales,read_markets,read_themes,write_themes,read_locations,read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects"

[auth]
redirect_urls = [
  "https://predictaseo-core-production.up.railway.app/auth/callback",
  "https://predictaseo-core-production.up.railway.app/auth/shopify/callback",
  "https://predictaseo-core-production.up.railway.app/api/auth/callback"
]
